### ISSUE TITLE
.opleidingen

### ISSUE THREAD

**Issue by anneliesvanminsel** [NHorward/De-VeSt---Black-#10]
Er wordt twee keer een klasse .opleidingen aangeroepen in de style.css

**Comment by NHorward** [comment]
In mijn opleidingen CSS heb ik dit aangepast, de .opleidingen voor de index blijft, de .opleidingen voor de opleidingen heb ik een andere naam gekregen. Ik zal dit bij het samenvoegen nog aanpassen in de algemene css.
