### ISSUE TITLE
Alle links toevoegen en controleren 

### ISSUE THREAD

**Issue by NHorward** [NHorward/De-VeSt---Black-#14]
Alle links op alle pagina's controleren.

**Comment by anneliesvanminsel** [comment]
In de footer zouden bij 'aanbod' nog de links moeten gezet worden.
Dit is in orde voor home en team.  
-- UPDATE:
Nu ook voor GKM en HL.

**Comment by anneliesvanminsel** [comment]
Op aanbod.html moet het vakje naar opleidingen aangepast worden naar 'opleidingsfasen'.
