### ISSUE TITLE
Code van commentaar voorzien en bronnen toevoegen

### ISSUE THREAD

**Issue by NHorward** [NHorward/De-VeSt---Black-#20]
Op eigen pagina's commentaar toevoegen aan de html en css voor gemakkelijk gebruik achteraf.

**Comment by anneliesvanminsel** [comment]
Normaal gezien hoeven wij dit eigenlijk niet te doen. 
Ik heb mijn nota's van hun voorstelling (dag 1) eens bekeken en daar staat in dat ze onze ideeën, code en designs meenemen naar iemand die het dan voor hun echt maakt. Dus die back-end is niet "ons probleem". 

Ik ben alleszins zoveel mogelijk in commentaar aan het zetten, maar we kunnen moeilijk achterelk stukje code schrijven wat het nu juist doet :/

**Comment by NHorward** [comment]
Da's waar!

Wel nog toevoegen:
- Groep, groepsnamen, academiejaar bovenaan elke pagina 
- Bronnen voor de teksten en foto's
