### ISSUE TITLE
De gevreesde grote samenvoeging van alle CSS 

### ISSUE THREAD

**Issue by NHorward** [NHorward/De-VeSt---Black-#21]
Alle css in een bestand samenvoegen.

**Comment by YolanCristoria** [comment]
De mijne steekt er al reeds in! ;)

**Comment by anneliesvanminsel** [comment]
Team en index zitten ook al in de algemene CSS!

**Comment by NHorward** [comment]
Aanbod, opleidingen en praktische info zijn toegevoegd aan de algemene CSS 😄
