### ISSUE TITLE
Leerkrachten - verborgen images

### ISSUE THREAD

**Issue by anneliesvanminsel** [NHorward/De-VeSt---Black-#5]
Op de team-page sectie leerkrachten:
Hier worden de lkr'en op gelijst maar de images moeten hieraan gekoppeld worden, en die zouden moeten verschijnen bij focus/click/hover. 

Hoe maak ik dat aan in HTML ? 
een ul met 30 li-elementen ? #help

**Comment by NHorward** [comment]
Je zou een spritesheet kunnen maken met de foto's van alle leerkrachten, dat gaat Tom helemaal geweldig vinden 👍 

Geen 30 li's en geen 30 foto's, maar zoals je al zei, is dit wel moeilijk als het leerkrachtenteam verandert... 

Iemand anders nog een oplossing?

**Comment by anneliesvanminsel** [comment]
Je kan met een li-werken waarin een a-tag staat en images. Deze kunnen dan verschijnen bij :focus en :hover. Dat gaat me wel lukken omdat zo te maken, is niet zoveel code om te schrijven.
