### ISSUE TITLE
Foto's / video's op opleidingen pagina

### ISSUE THREAD

**Issue by NHorward** [NHorward/De-VeSt---Black-#7]
De gekleurde blokken hebben allemaal een andere hoogte (door de verschillende inhoud), waardoor er nu altijd een gekleurde rand om de foto's zichtbaar is. Het valt niet heel erg op, maar het zou leuker zijn om dit weg te werken. 

De blokken allemaal een vaste hoogte geven lijkt me geen goed plan ivm verschillende schermgroottes. 

Bijkomende vraag: blijven het foto's of maken wij er video's van?

**Comment by anneliesvanminsel** [comment]
Zet de foto's op een height: 100%. Dan gaan ze wel niet mooi op een grid uitkomen maar passen ze wel mooi in de hoogte :D

**Comment by NHorward** [comment]
@anneliesvanminsel Dat heb ik al geprobeerd, maar het lukt niet... misschien omdat mijn article geen hoogte heeft? Zullen we er anders morgen samen eens naar kijken? :)

**Comment by anneliesvanminsel** [comment]
Ja, we zullen er morgen samen naar kijken! Ik heb dat namelijk ook nodig voor die nieuws-sectie op de home-page! 💃

**Comment by NHorward** [comment]
Voor grotere schermen opgelost door padding weg te halen, width van de foto's iets groter te maken en overflow: hidden toe te passen. 

Werkt nog niet goed op kleinere schermen, nog oplossen bij het responsive maken.
